//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADCS.CertMod.Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DebugString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebugString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADCS.CertMod.Demo.Properties.DebugString", typeof(DebugString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Exit::ctor].
        /// </summary>
        internal static string EXIT_CTOR {
            get {
                return ResourceManager.GetString("EXIT_CTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Exit::GetDescription].
        /// </summary>
        internal static string EXIT_GETDESCRIPTION {
            get {
                return ResourceManager.GetString("EXIT_GETDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit::GetManageModule].
        /// </summary>
        internal static string EXIT_GETMANAGEMODULE {
            get {
                return ResourceManager.GetString("EXIT_GETMANAGEMODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Exit::Initialize]
        ///    strConfig: {0}.
        /// </summary>
        internal static string EXIT_INITIALIZE {
            get {
                return ResourceManager.GetString("EXIT_INITIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Exit::Notify]
        ///    ExitEvent : {0}
        ///    Context   : {1}.
        /// </summary>
        internal static string EXIT_NOTIFY {
            get {
                return ResourceManager.GetString("EXIT_NOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ExitManage::Configure]
        ///    strConfig          : {0}
        ///    strStorageLocation : {1}
        ///    flags              : {2}.
        /// </summary>
        internal static string EXITMANAGE_CONFIGURE {
            get {
                return ResourceManager.GetString("EXITMANAGE_CONFIGURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ExitManage::ctor].
        /// </summary>
        internal static string EXITMANAGE_CTOR {
            get {
                return ResourceManager.GetString("EXITMANAGE_CTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ExitManage::ctor2].
        /// </summary>
        internal static string EXITMANAGE_CTOR2 {
            get {
                return ResourceManager.GetString("EXITMANAGE_CTOR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ExitManage::GetProperty]
        ///    strConfig          : {0}
        ///    strStorageLocation : {1}
        ///    strPropertyName    : {2} 
        ///    flags              : {3}.
        /// </summary>
        internal static string EXITMANAGE_GETPROPERTY {
            get {
                return ResourceManager.GetString("EXITMANAGE_GETPROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ExitManage::SetProperty]
        ///    strConfig          : {0}
        ///    strStorageLocation : {1}
        ///    strPropertyName    : {2} 
        ///    flags              : {3}
        ///    pvarProperty       : {4}.
        /// </summary>
        internal static string EXITMANAGE_SETPROPERTY {
            get {
                return ResourceManager.GetString("EXITMANAGE_SETPROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Policy::ctor].
        /// </summary>
        internal static string POLICY_CTOR {
            get {
                return ResourceManager.GetString("POLICY_CTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Policy::GetDescription].
        /// </summary>
        internal static string POLICY_GETDESCRIPTION {
            get {
                return ResourceManager.GetString("POLICY_GETDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Policy::GetManageModule].
        /// </summary>
        internal static string POLICY_GETMANAGEMODULE {
            get {
                return ResourceManager.GetString("POLICY_GETMANAGEMODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Policy::Initialize]
        ///    strConfig: {0}.
        /// </summary>
        internal static string POLICY_INITIALIZE {
            get {
                return ResourceManager.GetString("POLICY_INITIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Policy::Shutdown].
        /// </summary>
        internal static string POLICY_SHUTDOWN {
            get {
                return ResourceManager.GetString("POLICY_SHUTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Policy::VerifyRequest]
        ///    NativeResult : {0}
        ///    NewRequest   : {1}.
        /// </summary>
        internal static string POLICY_VERIFYREQUEST {
            get {
                return ResourceManager.GetString("POLICY_VERIFYREQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PolicyManage::Configure]
        ///    strConfig          : {0}
        ///    strStorageLocation : {1}
        ///    flags              : {2}.
        /// </summary>
        internal static string POLICYMANAGE_CONFIGURE {
            get {
                return ResourceManager.GetString("POLICYMANAGE_CONFIGURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PolicyManage::ctor].
        /// </summary>
        internal static string POLICYMANAGE_CTOR {
            get {
                return ResourceManager.GetString("POLICYMANAGE_CTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PolicyManage::ctor2].
        /// </summary>
        internal static string POLICYMANAGE_CTOR2 {
            get {
                return ResourceManager.GetString("POLICYMANAGE_CTOR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PolicyManage::GetProperty]
        ///    strConfig          : {0}
        ///    strStorageLocation : {1}
        ///    strPropertyName    : {2} 
        ///    flags              : {3}.
        /// </summary>
        internal static string POLICYMANAGE_GETPROPERTY {
            get {
                return ResourceManager.GetString("POLICYMANAGE_GETPROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PolicyManage::SetProperty]
        ///    strConfig          : {0}
        ///    strStorageLocation : {1}
        ///    strPropertyName    : {2} 
        ///    flags              : {3}
        ///    pvarProperty       : {4}.
        /// </summary>
        internal static string POLICYMANAGE_SETPROPERTY {
            get {
                return ResourceManager.GetString("POLICYMANAGE_SETPROPERTY", resourceCulture);
            }
        }
    }
}
